# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/serg/qt/simple_http_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/serg/qt/simple_http_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serg/qt/simple_http_server/CMakeFiles /home/serg/qt/simple_http_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serg/qt/simple_http_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named server_autogen

# Build rule for target.
server_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_autogen
.PHONY : server_autogen

# fast build rule for target.
server_autogen/fast:
	$(MAKE) -f CMakeFiles/server_autogen.dir/build.make CMakeFiles/server_autogen.dir/build
.PHONY : server_autogen/fast

handler.o: handler.cpp.o

.PHONY : handler.o

# target to build an object file
handler.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/handler.cpp.o
.PHONY : handler.cpp.o

handler.i: handler.cpp.i

.PHONY : handler.i

# target to preprocess a source file
handler.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/handler.cpp.i
.PHONY : handler.cpp.i

handler.s: handler.cpp.s

.PHONY : handler.s

# target to generate assembly for a file
handler.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/handler.cpp.s
.PHONY : handler.cpp.s

httpserver.o: httpserver.cpp.o

.PHONY : httpserver.o

# target to build an object file
httpserver.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/httpserver.cpp.o
.PHONY : httpserver.cpp.o

httpserver.i: httpserver.cpp.i

.PHONY : httpserver.i

# target to preprocess a source file
httpserver.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/httpserver.cpp.i
.PHONY : httpserver.cpp.i

httpserver.s: httpserver.cpp.s

.PHONY : httpserver.s

# target to generate assembly for a file
httpserver.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/httpserver.cpp.s
.PHONY : httpserver.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/main.cpp.s
.PHONY : main.cpp.s

response.o: response.cpp.o

.PHONY : response.o

# target to build an object file
response.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/response.cpp.o
.PHONY : response.cpp.o

response.i: response.cpp.i

.PHONY : response.i

# target to preprocess a source file
response.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/response.cpp.i
.PHONY : response.cpp.i

response.s: response.cpp.s

.PHONY : response.s

# target to generate assembly for a file
response.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/response.cpp.s
.PHONY : response.cpp.s

server_autogen/mocs_compilation.o: server_autogen/mocs_compilation.cpp.o

.PHONY : server_autogen/mocs_compilation.o

# target to build an object file
server_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_autogen/mocs_compilation.cpp.o
.PHONY : server_autogen/mocs_compilation.cpp.o

server_autogen/mocs_compilation.i: server_autogen/mocs_compilation.cpp.i

.PHONY : server_autogen/mocs_compilation.i

# target to preprocess a source file
server_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_autogen/mocs_compilation.cpp.i
.PHONY : server_autogen/mocs_compilation.cpp.i

server_autogen/mocs_compilation.s: server_autogen/mocs_compilation.cpp.s

.PHONY : server_autogen/mocs_compilation.s

# target to generate assembly for a file
server_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_autogen/mocs_compilation.cpp.s
.PHONY : server_autogen/mocs_compilation.cpp.s

worker.o: worker.cpp.o

.PHONY : worker.o

# target to build an object file
worker.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/worker.cpp.o
.PHONY : worker.cpp.o

worker.i: worker.cpp.i

.PHONY : worker.i

# target to preprocess a source file
worker.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/worker.cpp.i
.PHONY : worker.cpp.i

worker.s: worker.cpp.s

.PHONY : worker.s

# target to generate assembly for a file
worker.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/worker.cpp.s
.PHONY : worker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... edit_cache"
	@echo "... server_autogen"
	@echo "... handler.o"
	@echo "... handler.i"
	@echo "... handler.s"
	@echo "... httpserver.o"
	@echo "... httpserver.i"
	@echo "... httpserver.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... response.o"
	@echo "... response.i"
	@echo "... response.s"
	@echo "... server_autogen/mocs_compilation.o"
	@echo "... server_autogen/mocs_compilation.i"
	@echo "... server_autogen/mocs_compilation.s"
	@echo "... worker.o"
	@echo "... worker.i"
	@echo "... worker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

